
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'


// const {uploadPhoto, changephoto} =useState("");

async function handleformSubmit(event){
event.preventDefault();
// action=""


// console.log(event)
const form = event.currentTarget;
const fileInput = Array.from(form.elements).find(({name}) => name === 'file' )

const formdata = new FormData();

for ( const file of fileInput.files) {
  formdata.append('file', file); 
}

formdata.append('upload_preset','dddddd');

const data = await fetch("api/report",{
  method:"POST",
  body: formdata
}).then((res) => console.log(res));

}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WatchMan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi, welcome to WatchMan
        </h1>

        <p className={styles.description}>
          Need to report an Environmental Pollution?
        </p>

        <div className={styles.form}>
          <form method="post" onSubmit={handleformSubmit} enctype="multipart/form-data">
            <div className={styles.formGroup}>
              <label for="first">First name</label>
              <input type="text" id="first" name="first" className={styles.formInput} />
            </div>
            <div className={styles.formGroup}>
              <label for="last">Last name</label>
              <input type="text" id="last" name="last" className={styles.formInput}  />
            </div>
            <div className={styles.formGroup}>
              <label for="where">Where did you see it?</label>
              <input type="text" id="where" name="where" className={styles.formInput} />
            </div>
            <div className={styles.formGroup}>
              <label for="photofile">Upload a picture of it</label>
              <input type="file" id="photofile" name="file" className={styles.formInput} />
            </div>
              
              {/* {<img src} */}

              <button type="submit" className={style.formBtn}>Submit</button>
            </form>
        </div>
            
         

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/desmondezo1"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built with {' '}
          <span className={styles.logo}>
          💖
          </span>
        </a>
      </footer>
    </div>
  )
}
